# Generated by Django 2.2.2 on 2019-07-03 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApkFile',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('apk', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('appName', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('screen', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('level', models.CharField(default='Z', max_length=128)),
                ('nike_name', models.CharField(default='', max_length=128)),
                ('username', models.CharField(blank=True, default='', max_length=128, unique=True)),
                ('Email', models.EmailField(blank=True, max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('sex', models.CharField(blank=True, choices=[('female', '男'), ('male', '女')], default='男', max_length=128)),
                ('profile_photo', models.ImageField(default='media/about.png', upload_to='media')),
                ('register_time', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppDetail',
            fields=[
                ('app_type', models.CharField(blank=True, default='软件', max_length=128)),
                ('title', models.CharField(blank=True, default='----', max_length=128)),
                ('des', models.TextField()),
                ('downloadUrl', models.URLField()),
                ('iconUrl', models.URLField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('packetName', models.CharField(max_length=128)),
                ('size', models.IntegerField(default='0')),
                ('stars', models.FloatField()),
                ('author', models.CharField(blank=True, max_length=128)),
                ('version', models.CharField(blank=True, default='---', max_length=128)),
                ('downloadNum', models.CharField(blank=True, default='--', max_length=128)),
                ('date', models.DateField()),
                ('picture', models.ImageField(default='media\\ic_launcher.png', upload_to='media')),
                ('safe', models.CharField(blank=True, default='safe', max_length=128)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appstore.Screen')),
            ],
        ),
    ]
